version: "1.0"
fail_fast: true
stages:
  - prepare
  - release

steps:
  clone:
    stage: prepare
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  build_shell:
    stage: prepare
    title: Build shell
    type: build
    working_directory: "${{clone}}/pipeline"
    registry: utility
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BUILD_ID}}
    disable_push: true

  build:
    stage: release
    title: Build
    image: "${{build_shell}}"
    working_directory: "${{clone}}"
    commands:
      - make crossbuild
