version: "1.0"
fail_fast: true
stages:
  - test

steps:
  clone:
    stage: test
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  build_shell:
    title: Build shell
    type: build
    working_directory: "${{clone}}/pipeline"
    registry: utility
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BUILD_ID}}
    disable_push: true

  test:
    stage: test
    title: Test
    image: "${{build_shell}}"
    working_directory: "${{clone}}"
    commands:
      - gpg --import test/testing-key.pgp
      - make test build
