version: "1.0"
fail_fast: true
stages:
  - test

steps:
  clone:
    stage: test
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  test:
    stage: test
    title: Test
    image: 289698421666.dkr.ecr.us-east-1.amazonaws.com/codefresh/shell:0.1.0
    working_directory: "${{clone}}"
    commands:
      - gpg --import test/testing-key.pgp
      - make test build
